### ISSUE TITLE
Make the project work in Windows.

### ISSUE THREAD

**Issue by francescortiz** [francescortiz/rust-ear-trainer#1]

**Comment by arieltools** [comment]
While running with `cargo run`. It could be that I can't run `cargo` directly from the PATH yet. Will check again once I restart.

```
C:\_work\Code\rust-ear>c:\Users\ari\.cargo\bin\cargo.exe run
   Compiling libsqlite3-sys v0.26.0
   Compiling midir v0.9.1
error: failed to run custom build command for `libsqlite3-sys v0.26.0`

Caused by:
  process didn't exit successfully: `C:\_work\Code\rust-ear\target\debug\build\libsqlite3-sys-645a311ffdb3739d\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SQLITE3_INCLUDE_DIR
  cargo:rerun-if-env-changed=SQLITE3_LIB_DIR
  cargo:rerun-if-env-changed=SQLITE3_STATIC
  cargo:rerun-if-env-changed=VCPKGRS_DYNAMIC
  cargo:link-target=sqlite3
  cargo:rerun-if-env-changed=SQLITE3_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=SQLITE3_STATIC
  cargo:rerun-if-env-changed=SQLITE3_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SQLITE3_STATIC
  cargo:rerun-if-env-changed=SQLITE3_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-link-lib=dylib=sqlite3

  --- stderr
  thread 'main' panicked at C:\Users\ari\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libsqlite3-sys-0.26.0\build.rs:372:14:
  Could not copy bindings to output directory: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by francescortiz** [comment]
In the end instructing `libsqlite-sys` to use the bundle sqlite instead of the one provided by the operating system was enough to make the project build for windows.

```toml
[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]
```

**Comment by arieltools** [comment]
Compiling hashlink v0.6.0
   Compiling libsqlite3-sys v0.20.1
error: failed to run custom build command for `libsqlite3-sys v0.20.1`

Caused by:
  process didn't exit successfully: `C:\_work\Code\rust-ear\target\debug\build\libsqlite3-sys-2de3fca7297260a2\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at C:\Users\ari\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libsqlite3-sys-0.20.1\build.rs:59:18:
  Could not copy bindings to output directory: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
